# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\junyu\OneDrive\temp\info.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.setEnabled(True)
        Dialog.resize(230, 635)
        Dialog.setSizeGripEnabled(True)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 9, 211, 621))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_onlyui = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_onlyui.setGeometry(QtCore.QRect(10, 350, 71, 16))
        self.radioButton_onlyui.setChecked(True)
        self.radioButton_onlyui.setObjectName("radioButton_onlyui")
        self.radioButton_onlydoc = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_onlydoc.setEnabled(True)
        self.radioButton_onlydoc.setGeometry(QtCore.QRect(80, 350, 81, 16))
        self.radioButton_onlydoc.setObjectName("radioButton_onlydoc")
        self.radioButton_both = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_both.setEnabled(True)
        self.radioButton_both.setGeometry(QtCore.QRect(160, 350, 51, 16))
        self.radioButton_both.setObjectName("radioButton_both")
        self.pushButton_DocLocation = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_DocLocation.setEnabled(False)
        self.pushButton_DocLocation.setGeometry(QtCore.QRect(170, 370, 31, 23))
        self.pushButton_DocLocation.setCheckable(False)
        self.pushButton_DocLocation.setObjectName("pushButton_DocLocation")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 54, 12))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit_FindList = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_FindList.setGeometry(QtCore.QRect(10, 70, 191, 121))
        self.plainTextEdit_FindList.setObjectName("plainTextEdit_FindList")
        self.pushButton_ReplaceForA = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_ReplaceForA.setGeometry(QtCore.QRect(10, 400, 91, 31))
        self.pushButton_ReplaceForA.setObjectName("pushButton_ReplaceForA")
        self.checkBox_ForOnce = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_ForOnce.setGeometry(QtCore.QRect(110, 400, 81, 16))
        self.checkBox_ForOnce.setObjectName("checkBox_ForOnce")
        self.label_find = QtWidgets.QLabel(self.groupBox)
        self.label_find.setGeometry(QtCore.QRect(140, 50, 61, 16))
        self.label_find.setObjectName("label_find")
        self.label_replace = QtWidgets.QLabel(self.groupBox)
        self.label_replace.setGeometry(QtCore.QRect(150, 200, 61, 16))
        self.label_replace.setObjectName("label_replace")
        self.plainTextEdit_ReplaceList = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_ReplaceList.setGeometry(QtCore.QRect(10, 220, 191, 121))
        self.plainTextEdit_ReplaceList.setObjectName("plainTextEdit_ReplaceList")
        self.pushButton_fromExcel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_fromExcel.setGeometry(QtCore.QRect(10, 20, 141, 21))
        self.pushButton_fromExcel.setObjectName("pushButton_fromExcel")
        self.pushButton_SaveExcel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_SaveExcel.setGeometry(QtCore.QRect(160, 20, 41, 21))
        self.pushButton_SaveExcel.setObjectName("pushButton_SaveExcel")
        self.comboBox_DocLocation = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_DocLocation.setGeometry(QtCore.QRect(10, 370, 151, 22))
        self.comboBox_DocLocation.setStatusTip("")
        self.comboBox_DocLocation.setObjectName("comboBox_DocLocation")
        self.pushButton_shift = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_shift.setGeometry(QtCore.QRect(70, 196, 51, 20))
        self.pushButton_shift.setMinimumSize(QtCore.QSize(21, 0))
        self.pushButton_shift.setObjectName("pushButton_shift")
        self.checkBox_ForReplace = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_ForReplace.setEnabled(False)
        self.checkBox_ForReplace.setGeometry(QtCore.QRect(110, 420, 81, 16))
        self.checkBox_ForReplace.setObjectName("checkBox_ForReplace")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 440, 211, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.plainTextEdit_Output = QtWidgets.QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit_Output.setGeometry(QtCore.QRect(10, 20, 191, 161))
        self.plainTextEdit_Output.setReadOnly(True)
        self.plainTextEdit_Output.setObjectName("plainTextEdit_Output")

        self.retranslateUi(Dialog)
        self.radioButton_onlydoc.toggled['bool'].connect(self.pushButton_DocLocation.setEnabled)
        self.radioButton_both.toggled['bool'].connect(self.pushButton_DocLocation.setEnabled)
        self.radioButton_onlydoc.toggled['bool'].connect(self.checkBox_ForReplace.setEnabled)
        self.radioButton_both.toggled['bool'].connect(self.checkBox_ForReplace.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "全文替换"))
        self.groupBox.setTitle(_translate("Dialog", "基本参数"))
        self.radioButton_onlyui.setText(_translate("Dialog", "仅本程序"))
        self.radioButton_onlydoc.setText(_translate("Dialog", "仅Docx文档"))
        self.radioButton_both.setText(_translate("Dialog", "全部"))
        self.pushButton_DocLocation.setToolTip(_translate("Dialog", "点击选择需要替换的文档，可多选"))
        self.pushButton_DocLocation.setText(_translate("Dialog", "…"))
        self.label_2.setText(_translate("Dialog", "查找内容："))
        self.label_3.setText(_translate("Dialog", "替换为："))
        self.pushButton_ReplaceForA.setText(_translate("Dialog", "全部替换"))
        self.checkBox_ForOnce.setToolTip(_translate("Dialog", "勾选则只会替换第一次。"))
        self.checkBox_ForOnce.setText(_translate("Dialog", "仅替换一次"))
        self.label_find.setText(_translate("Dialog", "数量：0"))
        self.label_replace.setText(_translate("Dialog", "数量：0"))
        self.pushButton_fromExcel.setToolTip(_translate("Dialog", "从保存的EXCEL文件内导入查找、替换列表。"))
        self.pushButton_fromExcel.setText(_translate("Dialog", "从EXCEL载入列表"))
        self.pushButton_SaveExcel.setToolTip(_translate("Dialog", "将替换列表生成Excel文件"))
        self.pushButton_SaveExcel.setText(_translate("Dialog", "生成"))
        self.comboBox_DocLocation.setToolTip(_translate("Dialog", "下拉查看已选择的文件"))
        self.pushButton_shift.setToolTip(_translate("Dialog", "交换查找和替换关键词"))
        self.pushButton_shift.setText(_translate("Dialog", "▲ ▼"))
        self.checkBox_ForReplace.setToolTip(_translate("Dialog", "勾选则只会替换第一次。"))
        self.checkBox_ForReplace.setText(_translate("Dialog", "覆盖原文件"))
        self.groupBox_2.setTitle(_translate("Dialog", "结果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

